import Head from 'next/head'

import Nav from '../components/Nav'

export default function Contact() {
  return (
    <div >
      <Head>
        <title>My website - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>

      <main>hello</main>

    </div>
  )
}