import Head from 'next/head'
import Image from 'next/image'

import Nav from '../components/Nav'

export default function Home() {
  return (
    <div >
      <Head>
        <title>My website - home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>

      <header>
    <div className="center">
      <Image className='imagep' src="/img/fotop.JPG" alt="minha foto" width="120px" height="120px" />
    </div>
    <h1>Ronaldo Farias</h1>
    <h2>Software developer</h2>
  </header>

      <main>
        <section>
        <h3>About </h3>
        <p>
        I am a technical in electronics who started learning to program micro controllers.
        Later I started programming webpages and fell in love with it
      </p>
      <h3>Formation</h3>
      <p>
        Web Design - Humber College - 2022 
        Game Design - Fatec Sao Caetano do Sul - 2013 
        Electronics Engineering Technician -Senai Roberto Simonsen - 2011
      </p>
      <h3>Course</h3>
      <p>
        Programming Foundations with JavaScript, HTML and CSS - Duke University - 2020

      </p>
        </section>
      </main>

    </div>
  )
}
