import Head from 'next/head'
import Image from 'next/image'
import Nav from '../components/Nav'

export default function project() {
  return (
    <div >
      <Head>
        <title>My website - Project</title>
        <meta nameName="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav>
        
      </Nav>

      <main><section className="projetos">
      <div className="card">

        <a href="https://capable-malabi-9fa00d.netlify.app/"><Image className="image" src="/img/book.jpg" class="d-block w-100" width="400px" height="194px"alt="Book"/></a>
        <h2>Book Resell</h2>
      </div>
      <div className="card">
      <a href="https://amazing-turing-b6b994.netlify.app/thriftstore/"><Image className="image" src="/img/SpendSmart.jpg" width="400px" class="d-block w-100"height="194px"alt="SpendSmart"/></a>
      <h2>Spend Smart</h2>
    </div>
      <div className="card">
      <a href="https://fabulous-starburst-3a76b4.netlify.app/"><Image className="image" src="/img/ecommerce.jpg"  width="400px" height="194px" alt="ecommerce"/> </a>
      <h2>Ecommerce</h2>
    </div>
      <div className="card">
      <a href="https://132roldan.github.io/EphemeralFilms/"><Image className="image" src="/img/ephemeral.jpg" class="d-block w-100" width="400px" height="194px" alt="ephemeral"/> </a>
      <h2>Ephemeral Films</h2>
    </div>
      <div className="card">
      <a href="https://hardcore-gates-1a5b5d.netlify.app/"><Image className="image" src="/img/curiosity.jpg"  width="400px" height="194px" alt="curiosity"/></a>
      <h2>Curiosity</h2>
    </div>
        
      
    </section></main>

    </div>
  )
}